name: Complete workflow

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.4]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run all tests
      run: yarn test

    - name: Push to Heroku
      run: git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/pedro-surf-forecast.git origin/main:main
