name: Complete workflow

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.4]

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run all tests
      run: yarn test

    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Add Heroku remote
      run: heroku git:remote --app $HEROKU_APP_NAME
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    - name: Push to Heroku
      run: git push heroku master
